### ISSUE TITLE
DIP28 PROBE Components

### ISSUE THREAD

**Issue by AMT-Cheif** [Kris-Sekula/EPROM-EMU-NG#17]
I'm trying to find dhe component to build the probe, but I can't find anywhere the dip28 header. the link to digikey you posted on your website not work anymore. Can you help me to find the header?

**Comment by Kris-Sekula** [comment]
The BOM is on GitHub (https://github.com/Kris-Sekula/EPROM-EMU-NG/blob/master/Hardware/2.2c/EpromEmu_2_2c_BoM_DigiKey.xlsx) the part number you are looking for is the: FDP-628-T (that is DigiKey pn: 2057-FDP-628-T-ND) ... The BoM link on my page is still correct, but since one of the parts is out of production you just have to mark it to be deleted and the list of parts will load up on DigiKey ... I'll update the list this week,  but with the current components shortage, it can be challenging to secure everything.
