### ISSUE TITLE
Bufferoverflow in Python script

### ISSUE THREAD

**Issue by hubertushirsch** [Kris-Sekula/EPROM-EMU-NG#5]
Hi Kris,

When uploading a binary ROM image, the 64k limit is not checked.
The script crashes when the file exceeds this limit.

Use case:
128kB image file for a target with 2 * 64kB EPROM (2 * 27512).
It is not a problem to burn the image in two EPROMs with an EPROM burner, as I can specify the start address in the file and the length in the burning software for each burn process.

The emulator is in the socket of the lower ROM.
During the upload, an attempt is made to load the complete file into the buffer, which leads to an overflow.

```
D:\<path>\>EPROM_EMU_NG_SW_Python_v2.1.2.py -mem 27512 -spi n -map y d:\<filepath>\file128k.bin com9
-------------------------
EPROM EMULATOR NG Script version 2.1.2 started - mygeekyhobby.com
Option 'use cache' is set to: disabled
Reading data from: d:\<filepath>\file128k.bin
Traceback (most recent call last):
  File "D:\<path>\EPROM_EMU_NG_SW_Python_v2.1.2.py", line 565, in <module>
    main()
  File "D:\<path>\EPROM_EMU_NG_SW_Python_v2.1.2.py", line 338, in main
    current_data = load_to_buffer(file)
  File "D:\<path>\EPROM_EMU_NG_SW_Python_v2.1.2.py", line 304, in load_to_buffer
    data_64k[x+startaddr] = binfile[x]
IndexError: list assignment index out of range

```
The buffer in the Python script is declared as 64kB.
A test as to whether the loading address (option -start <offset>) + file length is> 64kB should be implemented.
A warning should be issued for files that exceed the 64k limit and the upload should stop automatically when the 64k limit is reached.

On the other hand, it is not possible to plug the (or a second) emulator into the socket of the top ROM and load the top half of the file into the emulator. File offset = 0x10000, Loading address = 0x0000.
For this one would have to be able to specify an offset for the start in the file.

Of course, you can split the image file beforehand using suitable tools. But during a development process this would be an additional step that would have to be repeated after each ASM / compiler run.

Ralf

**Comment by hubertushirsch** [comment]
Another aspect:
Suppose I have a 4kB binary file for a target, which is physically equipped with 2 * 2kB EPROM (2716).
The problem of loading only the upper half of the image for the second EPROM into the emulator is as already described.

If I only want to emulate the lower EPROM, 4kB are still loaded into the emulators SRAM and/or SPI, although only 2kB are required for the 2716. The bus is also set to type 2716 so that the third and fourth kilobytes are never addressed.

Should one (this is only to be understood as a discussion) limit the amount of data to be uploaded to the size of the selected EPROM type? Or what is the philosophy behind the current implementation of uploading the complete file?

Ralf

**Comment by hubertushirsch** [comment]
Hi Kris

Here is a suggestion from me to limit the file loading process to the ROM size and the 64k address space.
I've only tested it with full images. I have not checked the function when using the cache mode.

Ralf
[EPROM_EMU_NG_SW_Python_v2.1.2update1.diff.txt](https://github.com/Kris-Sekula/EPROM-EMU-NG/files/5860547/EPROM_EMU_NG_SW_Python_v2.1.2update1.diff.txt)

**Comment by Kris-Sekula** [comment]
Hi Ralf,

2.1.2 is not public yet, so only the members of the groups.io are experimenting with it, so for now I'm not going to post any fixes here.

The first version of my python control script had those checks baked in, but after I added the hex file support, those checks were a bit trickier to implement. Adding a check for .bin is half of the story, I also need to make sure we do the same checks for .hex. 

Regarding the adjustment of the file boundary to support splitting the image across multiple Lower / Higher EPROMs, I'm still not convinced if the emulator script should be responsible for doing that. Of course, we can add this function, but with many corner cases and all sorts of things to consider, I wonder if we should let another program do this job. If you are developing firmware, I'm sure you are not using GUI mode, but have some kind of .bat or .sh or make file, so adding one more command to adjust the files before they go to the EPROM emulator should be easy to do, I use this well-established EPROM load files manipulation program: https://sourceforge.net/projects/srecord/
Even the people behind the commercial Keil compiler recommend it. The program was in development since 2003 ... and it took them almost 10 years to get to a stable state, so I'm worried the moment I add one manipulation use case to my script, there will be another and another, etc.

Thanks again for your helpful contributions and remarks, you've been the biggest and most serious contributor to the firmware / software of the emulator so far. Good job!

Kris

**Comment by hubertushirsch** [comment]
Hi Kris,

> 2.1.2 is not public yet,

the changes I sent you, of course, also work in the published version EPROM_NG_v2.0rc3.py.
Since I was only working with the preliminary version recently, I did not think about it when implementing my ideas.

I would definitely recommend the 64k overflow test for binary files. In Intel Hex only 16bit addresses are possible, because this problem does not exist.

Reducing the uploaded bytes to the size of the selected EPROM was an idea in order to save upload time, since the data behind the EPROM size in the SRAM is never addressed. And to prevent unnecessary write operations in the SPI EEPROM.
 
Selecting individual EPROMs in multi-EPROM images (file offset) was also an idea. Of course you can do a split with external tools. I know **srecord**. I have just implemented the option of specifying a file offset. If there is no interest, I will not go any further.

Ralf

**Comment by Kris-Sekula** [comment]
Ralf,

Added your changes to 2.1.rc4 shared on groups.io, checks for data outside of selected memory type are now done for both bin and hex files.

Kris
