### ISSUE TITLE
Adapter for dual 27c256? (For IBM 5140)

### ISSUE THREAD

**Issue by prozacgod** [Kris-Sekula/EPROM-EMU-NG#6]
So I'm a fairly green electronics hobbyist, and I was wondering if it would be easy to make this work on the IBM 5140's dual socket interface, probably with some form of daughter/adapter board.

I found references to the original roms here, and they're listed as 27c256

http://www.minuszerodegrees.net/rom/rom.htm

I haven't confirmed that, but I assume since there's a dumped rom file there, it's probably accurate.

Any thoughts?

**Comment by prozacgod** [comment]
A bit more information

This page: 
http://ohlandl.ipv7.net/5140/5140.html

Lists the roms as "SMM6326CBK"

**Comment by Kris-Sekula** [comment]
Hi,
I'm not that familiar with the 5140 but when I see two ROM it will either
mean:
1. They used two x 27256 as this was the max size that was cheap enough to
fit the code into - in that case you can just use a single emulator
(utilizing the 64k memory it can emulate) and probably a simple adapter to
get the signals decoded into the right place.
2. they used two chips because they want to get the 16bit data bus. In that
case, you will need two emulators, to give you the 16bit data bus. They
show up on your computer as serial ports and you can control them
individually, we could even modify the control script to manage two
emulators from a single command or something like that.

Hope that helps
Kris

**Comment by prozacgod** [comment]
Oh, that's a good point about the bus size - I just pulled some of the code into a debugger, and it's looking like it's flat data just on 2 rom files, so that's good.

I'm guessing here, but bear with me - if I need to make this "larger eprom" fit the smaller eprom, I need to tie the CS lines from both sockets through an or gate, into the emulators CS line, and the CS line from the eprom higher in address space into the a15 address line on the emulator?

this ... sounds close?

P.S. - Thanks for such a fast reply!

**Comment by Kris-Sekula** [comment]
"I'm guessing here, but bear with me - if I need to make this "larger
eprom" fit the smaller eprom, I need to tie the CS lines from both sockets
through an or gate, into the emulators CS line, and the CS line from the
eprom higher in address space into the a15 address line on the emulator?"

spot on! without the schematic diagram to confirm, I would take the exact
same assumption...CS lines from both sockets via an OR gate (you could use
a two diode OR gate approach instead of an actual OR gate) and A15 from one
of the sockets CS signal ... Depending on implementation they might be
controlling the OE and/or the CS in the 27C256...Try to dig out the actual
schematic diagram so we can confirm the best approach.

Kris
